---
catalogue_url: https://catalogue.ogsl.ca
base_query: ""

map:
  center: [66.485, -62.48]
  zoom: 5

default_language: en
title:
  en: SLGO's Catalogue Map
  fr: Carte Catalogue de l'OGSL

metadata:
  en:
    title: SLGO's Catalogue Map
    description: SLGO Catalogue Map is a web application that allows users to visualize and explore the catalogue of SLGO.
  fr:
    title: Carte Catalogue de l'OGSL
    description: La carte du catalogue de l'OGSL est une application Web qui permet aux utilisateurs de visualiser et d'explorer le catalogue de l'OGSL.

theme:
  light: "#ffff"
  dark: "#0000"
  primary_color: "#3b82f6"
  accent_color: "#F6AF3B"

logos:
  main_light: "/Images/OGSL_NoTag.png"
  main_dark: "/Images/OGSL_NoTag_White.png"
  favicon: "/images/favicon.ico"

logo_default:
  en: "/Images/cioos-national_EN-01.png"
  fr: "/Images/cioos-national_FR-01.png"

