basePath: /custom-path

catalogue_url: https://catalogue.ogsl.ca
base_query: projects=*baseline*&rows=50

title:
  en: SLGO's Catalogue Map
  fr: Carte Catalogue de l'OGSL
metadata:
  en:
    title: SLGO's Catalogue Map
    description: SLGO Catalogue Map is a web application that allows users to visualize and explore the catalogue of SLGO.
  fr:
    title: Carte Catalogue de l'OGSL
    description: La carte du catalogue de l'OGSL est une application Web qui permet aux utilisateurs de visualiser et d'explorer le catalogue de l'OGSL.

theme:
  backgroundColor: "#f3f4f6"
  color: "#1f2937"
  backgroundColor_dark: "#111827"
  color_dark: "#e5e7eb"
  primary_color: "#3b82f6"
  accent_color: "#f97316"
  font: "'Inter', sans-serif"

logos:
  main_light: "/Images/OGSL_NoTag.png"
  main_dark: "/Images/OGSL_NoTag_White.png"
  favicon: "/images/favicon.ico"

